export type ProductCategory = "clothing" | "accessories" | "lifestyle" | "tattoos"
export type ShopCategory = "all" | ProductCategory
export type ProductBadge = "Bestseller" | "New" | "Sale" | null

export interface CatalogProduct {
  id: string
  name: string
  tagline: string
  description: string
  price: number
  originalPrice: number | null
  image: string
  badge: ProductBadge
  category: ProductCategory
  sizes: string[]
  details: string
  howToUse: string
  ingredients: string
  delivery: string
}

export const productCategories: ProductCategory[] = ["clothing", "accessories", "lifestyle", "tattoos"]

export const shopCategories: ShopCategory[] = ["all", ...productCategories]

export const shopCategoryLabels: Record<ShopCategory, string> = {
  all: "All",
  clothing: "Clothing",
  accessories: "Accessories",
  lifestyle: "Lifestyle",
  tattoos: "One-Time Tattoos",
}

export function isShopCategory(value: string | null | undefined): value is ShopCategory {
  return Boolean(value && shopCategories.includes(value as ShopCategory))
}

const standardDelivery =
  "Free standard shipping on orders over $50. Express delivery available at checkout. Orders ship within 1–2 business days."

const tattooDelivery =
  "Ships flat in protective sleeves. Free standard shipping on orders over $50. Orders typically dispatch within 1–2 business days."

export const catalogProducts: CatalogProduct[] = [
  {
    id: "lemon-dress",
    name: "Sunshine Lemon Dress",
    tagline: "Squeeze the day in style",
    description: "Vibrant yellow cotton dress with a cheerful lemon print for bright everyday styling.",
    price: 45,
    originalPrice: 55,
    image: "/placeholder.svg",
    badge: "Bestseller",
    category: "clothing",
    sizes: ["S", "M", "L", "XL"],
    details: "A breathable cotton dress with a softly cinched waist, relaxed skirt, and playful all-over print designed for sunny-day comfort.",
    howToUse: "Machine wash cold with like colors. Hang to dry or tumble dry low. Iron on low heat when needed.",
    ingredients: "100% cotton fabric, natural-feel lining, colorfast printed finish.",
    delivery: standardDelivery,
  },
  {
    id: "citrus-tote",
    name: "Citrus Canvas Tote",
    tagline: "Carry your sunshine everywhere",
    description: "Durable canvas tote bag built for everyday essentials with a bright citrus look.",
    price: 22,
    originalPrice: null,
    image: "/placeholder.svg",
    badge: "New",
    category: "accessories",
    sizes: ["One Size"],
    details: "A roomy carryall with reinforced handles, inner pocket storage, and a structured base for daily errands or weekend plans.",
    howToUse: "Spot clean with a damp cloth. Avoid bleach and machine drying to preserve shape and print quality.",
    ingredients: "Heavyweight cotton canvas with woven shoulder straps.",
    delivery: standardDelivery,
  },
  {
    id: "zest-candle",
    name: "Lemon Zest Candle",
    tagline: "A brighter mood in every room",
    description: "Fresh scented soy candle that brings a clean citrus glow to bedrooms, desks, and cozy corners.",
    price: 18,
    originalPrice: null,
    image: "/placeholder.svg",
    badge: null,
    category: "lifestyle",
    sizes: ["8 oz"],
    details: "Hand-poured soy wax candle with a cotton wick and soft citrus fragrance designed for a clean, even burn.",
    howToUse: "Trim wick to 1/4 inch before each use. Burn on a stable heat-safe surface for up to 3 hours at a time.",
    ingredients: "Soy wax blend, cotton wick, citrus fragrance oil.",
    delivery: standardDelivery,
  },
  {
    id: "spring-hat",
    name: "Spring Meadow Hat",
    tagline: "Shade with a soft floral finish",
    description: "Protective sun hat with charming floral details and an easy, lightweight fit.",
    price: 28,
    originalPrice: 35,
    image: "/placeholder.svg",
    badge: "Sale",
    category: "accessories",
    sizes: ["One Size"],
    details: "Wide-brim silhouette with a flexible structure and airy feel, made for vacations, park days, and warm-weather styling.",
    howToUse: "Store flat or gently hung. Spot clean only and avoid prolonged folding to preserve brim shape.",
    ingredients: "Woven straw blend with soft inner band and decorative trim.",
    delivery: standardDelivery,
  },
  {
    id: "lemon-tee",
    name: "Lemon Squeeze Tee",
    tagline: "Everyday comfort with a playful twist",
    description: "Organic cotton tee with a cheerful graphic and an easy relaxed fit for everyday wear.",
    price: 25,
    originalPrice: null,
    image: "/placeholder.svg",
    badge: null,
    category: "clothing",
    sizes: ["XS", "S", "M", "L", "XL"],
    details: "Soft-touch jersey tee with a slightly oversized cut, durable neckline, and versatile styling for layering or standalone wear.",
    howToUse: "Wash cold inside out with similar colors. Tumble dry low or line dry to maintain softness and print clarity.",
    ingredients: "100% organic cotton jersey.",
    delivery: standardDelivery,
  },
  {
    id: "lemon-socks",
    name: "Sour & Sweet Socks",
    tagline: "Tiny lemons, big comfort",
    description: "Comfortable everyday socks finished with miniature lemon patterns and a soft stretch fit.",
    price: 12,
    originalPrice: null,
    image: "/placeholder.svg",
    badge: "New",
    category: "clothing",
    sizes: ["S/M", "M/L"],
    details: "Cushioned sole, ribbed cuff, and lightweight knit structure designed for all-day comfort with sneakers, loafers, or lounge sets.",
    howToUse: "Machine wash warm with similar colors. Tumble dry low. Do not iron or bleach.",
    ingredients: "Cotton blend with stretch yarn for fit retention.",
    delivery: standardDelivery,
  },
  {
    id: "high-rise-pleated-mini",
    name: "High-Rise Pleated Mini Skirt",
    tagline: "Sharp lines, instant energy",
    description: "A flirty pleated mini with a clean high waist and easy movement for nights out, brunch plans, and styled-up everyday looks.",
    price: 42,
    originalPrice: 58,
    image: "https://img.kwcdn.com/product/fmket/2e849bc0b2cfe454c3c3f434dbea1b18.jpg",
    badge: "New",
    category: "clothing",
    sizes: ["XS", "S", "M", "L"],
    details: "Designed with a crisp pleated shape, soft drape, and comfortable waistband that pairs well with baby tees, fitted knits, or oversized blazers.",
    howToUse: "Wash cold on gentle cycle and reshape while damp. Hang dry to keep the pleats looking sharp.",
    ingredients: "Soft-touch woven blend with light structure and flexible waistband finish.",
    delivery: standardDelivery,
  },
  {
    id: "streetline-pleated-skirt",
    name: "Streetline A-Line Pleated Skirt",
    tagline: "A stronger silhouette for daily styling",
    description: "A versatile A-line skirt with a sharper streetwear edge and flattering high-rise shape for quick statement outfits.",
    price: 34,
    originalPrice: 46,
    image: "https://img.kwcdn.com/product/fmket/47a01d1e7b9359969b5c4555953f2898.jpg",
    badge: "Sale",
    category: "clothing",
    sizes: ["S", "M", "L", "XL"],
    details: "Made for tucked tanks, mesh layers, and cropped jackets with a silhouette that swings without losing shape.",
    howToUse: "Machine wash cold with dark colors and line dry. Steam lightly to refresh the pleats.",
    ingredients: "Poly blend shell with smooth inner feel and reinforced waistband seams.",
    delivery: standardDelivery,
  },
  {
    id: "rosewire-lace-set",
    name: "Rosewire Lace Bralette Set",
    tagline: "Soft structure with a bold finish",
    description: "A contrast lace lingerie set with adjustable straps, expressive detailing, and a comfortable fit that still feels statement-making.",
    price: 20,
    originalPrice: 29,
    image: "https://img.kwcdn.com/product/fancy/0927024b-bc2f-422d-9fc2-4e9e16202739.jpg",
    badge: "Bestseller",
    category: "clothing",
    sizes: ["S", "M", "L"],
    details: "Includes a lightweight bralette and matching bottoms designed for all-day comfort, layering, and elevated lounge styling.",
    howToUse: "Hand wash cold and lay flat to dry to preserve lace texture and elastic recovery.",
    ingredients: "Stretch lace, soft mesh lining, adjustable shoulder hardware, and flexible elastic trim.",
    delivery: standardDelivery,
  },
  {
    id: "nightfall-corset-top",
    name: "Nightfall Mesh Corset Top",
    tagline: "Defined shape, polished edge",
    description: "A fitted corset-style top with mesh structure, lace-up energy, and a sleek going-out silhouette.",
    price: 32,
    originalPrice: 45,
    image: "https://img.kwcdn.com/product/fmket/94367590bdbb86c3f353141ca96e3aae.jpg",
    badge: "New",
    category: "clothing",
    sizes: ["XS", "S", "M", "L"],
    details: "Built to style with denim, pleated skirts, or tailored pants thanks to supportive paneling and adjustable straps.",
    howToUse: "Spot clean or hand wash cold. Air dry away from direct heat to keep the shaping smooth.",
    ingredients: "Support mesh, stretch lining, rhinestone accents, and lace-up inspired trim.",
    delivery: standardDelivery,
  },
  {
    id: "midnight-lace-duo",
    name: "Midnight Lace Duo Set",
    tagline: "Lightweight lace for after-dark styling",
    description: "A semi-sheer lace bra and brief set designed to feel soft, flattering, and polished under fitted layers or lounge looks.",
    price: 22,
    originalPrice: 31,
    image: "https://img.kwcdn.com/product/fancy/6725d8a4-04f9-4b47-9a7d-b2104a447cef.jpg",
    badge: "New",
    category: "clothing",
    sizes: ["S", "M", "L"],
    details: "Features a V-neck lace bralette, matching briefs, and an easy stretch fit made for comfortable everyday wear.",
    howToUse: "Hand wash cold and lay flat to dry. Avoid bleach and rough agitation.",
    ingredients: "Semi-sheer lace, soft stretch elastic, and lightweight mesh support panels.",
    delivery: standardDelivery,
  },
  {
    id: "orbit-tracking-tripod",
    name: "Orbit Face-Tracking Tripod",
    tagline: "Hands-free filming with clean movement",
    description: "A smart face-tracking phone tripod built for livestreams, tutorials, creator setups, and easy solo content capture.",
    price: 135,
    originalPrice: 169,
    image: "https://img.kwcdn.com/product/21a488b5e6/48c3f8ba-5de5-46c9-8fbf-55b5133b801d_1280x1280.jpeg",
    badge: "New",
    category: "accessories",
    sizes: ["One Size"],
    details: "Features 360° tracking, an adjustable mount, and a stable tripod base for product filming, GRWM videos, and desk-friendly setups.",
    howToUse: "Unfold the base, mount your phone, and activate tracking mode before filming. Store fully collapsed after use.",
    ingredients: "ABS body, reinforced hinge points, stabilized tripod legs, and rechargeable tracking module.",
    delivery: standardDelivery,
  },
  {
    id: "neon-heart-ink-sheets",
    name: "Neon Heart Ink Sheets",
    tagline: "Playful one-time tattoos for bold looks",
    description: "A two-sheet set of bright heart temporary tattoos designed for parties, festivals, beach looks, and layered body-art styling.",
    price: 14,
    originalPrice: 19,
    image: "https://img.kwcdn.com/product/open/4730a9f2439949daa120de7ad2db32aa-goods.jpeg",
    badge: "New",
    category: "tattoos",
    sizes: ["2 Sheets"],
    details: "Packed with high-impact heart graphics in punchy pink and red tones for neck, arm, shoulder, or collarbone placement.",
    howToUse: "Apply to clean dry skin, press with water for 20–30 seconds, then peel away the backing. Remove gently with oil or micellar cleanser.",
    ingredients: "Skin-safe temporary pigment film, transfer paper backing, and cosmetic-grade adhesive.",
    delivery: tattooDelivery,
  },
  {
    id: "script-shadow-tattoo-sheet",
    name: "Script Shadow Tattoo Sheet",
    tagline: "Minimal phrases with sharp contrast",
    description: "A waterproof one-time tattoo sheet with dark scripted phrases and graphic accents for collarbone, arm, leg, or back placement.",
    price: 4,
    originalPrice: 7,
    image: "https://img.kwcdn.com/product/fmket/d2448c50109c200e3d858e4061b823a5.jpg",
    badge: null,
    category: "tattoos",
    sizes: ["1 Sheet"],
    details: "Great for layered styling, concert looks, and quick visual details when you want ink energy without long wear.",
    howToUse: "Trim around the artwork, press onto clean skin with a damp cloth, and let it set before dressing. Remove with cleansing oil.",
    ingredients: "Water-transfer temporary pigment, lightweight adhesive layer, and glossy protective film.",
    delivery: tattooDelivery,
  },
  {
    id: "love-note-ink-pack",
    name: "Love Note One-Time Ink Pack",
    tagline: "Romantic mini tattoos in seconds",
    description: "A five-piece set of one-time tattoo stickers featuring sweet phrase art made for date nights, photo shoots, and playful gifting.",
    price: 6,
    originalPrice: 10,
    image: "https://img.kwcdn.com/product/fancy/377e1a1d-63f0-4084-bb82-e979ec6d58b7.jpg",
    badge: "Sale",
    category: "tattoos",
    sizes: ["5 Pieces"],
    details: "Each pack includes compact word-based tattoo designs sized for wrists, shoulders, ankles, or layered torso placement.",
    howToUse: "Press each tattoo onto clean skin with water, allow to dry fully, and avoid heavy rubbing for longer wear.",
    ingredients: "Temporary transfer ink film, safe adhesive layer, and paper backing sheets.",
    delivery: tattooDelivery,
  },
  {
    id: "cherry-check-pleated-skirt",
    name: "Cherry Check Pleated Skirt",
    tagline: "Sharp pleats with a bold plaid finish",
    description: "A red plaid pleated mini skirt designed for concert looks, layered streetwear, and playful everyday styling.",
    price: 19,
    originalPrice: 27,
    image: "https://img.kwcdn.com/product/fancy/9c2a7387-134f-483f-90f8-4332184934c4.jpg",
    badge: "New",
    category: "clothing",
    sizes: ["XS", "S", "M", "L"],
    details: "Features a clean waistband, set pleats, and a swingy mini shape that pairs easily with fitted tops, sweaters, or boots.",
    howToUse: "Machine wash cold on gentle and hang to dry to help preserve pleat structure.",
    ingredients: "Plaid poly-viscose shell, lightweight lining, and stitched pleat setting.",
    delivery: standardDelivery,
  },
  {
    id: "after-dark-corset-bustier",
    name: "After Dark Corset Bustier",
    tagline: "Structured shine for going-out fits",
    description: "A rhinestone-trim corset bustier with contour seams and a sculpted silhouette made for after-dark styling.",
    price: 29,
    originalPrice: 39,
    image: "https://img.kwcdn.com/product/fmket/d5ff446ed5322bd74045f1a3f28654c0.jpg",
    badge: "Sale",
    category: "clothing",
    sizes: ["XS", "S", "M", "L"],
    details: "Designed with shaping seams, a fitted bodice, and embellished trim that works with skirts, denim, or layered jackets.",
    howToUse: "Hand wash cold and reshape while damp. Air dry flat to maintain the structured silhouette.",
    ingredients: "Stretch body fabric, soft inner mesh, rhinestone detailing, and flexible contour boning.",
    delivery: standardDelivery,
  },
  {
    id: "velvet-lace-bralette-set",
    name: "Velvet Lace Bralette Set",
    tagline: "Soft stretch lace with a polished finish",
    description: "A lightweight lace bralette and brief set made for easy layering, lounge looks, and fitted outfit styling.",
    price: 21,
    originalPrice: 29,
    image: "https://img.kwcdn.com/product/fancy/47b7aed4-05fc-4309-b63a-75f619df619b.jpg",
    badge: "New",
    category: "clothing",
    sizes: ["S", "M", "L"],
    details: "Includes a soft triangle bralette, matching brief, and flexible stretch finish designed for smooth all-day wear.",
    howToUse: "Hand wash cold and lay flat to dry. Avoid rough agitation to protect the lace texture.",
    ingredients: "Floral lace, soft stretch mesh, adjustable straps, and elastic support trim.",
    delivery: standardDelivery,
  },
  {
    id: "halo-smart-tripod-stand",
    name: "Halo Smart Tripod Stand",
    tagline: "Compact creator gear for solo shooting",
    description: "A compact smart tripod stand built for GRWM videos, desk tutorials, livestreams, and easy hands-free filming.",
    price: 98,
    originalPrice: 129,
    image: "https://img.kwcdn.com/product/fmket/03ee0ea96b266363be4007f85cb95477.jpg",
    badge: "New",
    category: "accessories",
    sizes: ["One Size"],
    details: "Features a stable folding base, adjustable phone mount, and tracking-ready head for smoother solo content capture.",
    howToUse: "Set the stand on a level surface, mount your phone securely, and adjust height before recording.",
    ingredients: "ABS frame, reinforced hinges, adjustable mount hardware, and rechargeable tracking head.",
    delivery: standardDelivery,
  },
  {
    id: "crimson-kiss-tattoo-duo",
    name: "Crimson Kiss Tattoo Duo",
    tagline: "Heart-led ink for playful outfit details",
    description: "A bold two-sheet temporary tattoo duo with bright heart artwork sized for collarbones, wrists, shoulders, and layered festival styling.",
    price: 12,
    originalPrice: 17,
    image: "https://img.kwcdn.com/product/open/4730a9f2439949daa120de7ad2db32aa-goods.jpeg",
    badge: "Sale",
    category: "tattoos",
    sizes: ["2 Sheets"],
    details: "Made for quick high-contrast styling moments, this duo gives you multiple heart motifs to mix across one look or split across separate outfits.",
    howToUse: "Apply to clean dry skin with water for 20–30 seconds, then peel carefully. Remove with cleansing oil when you want a clean reset.",
    ingredients: "Temporary transfer ink film, skin-safe adhesive layer, and glossy paper backing.",
    delivery: tattooDelivery,
  },
  {
    id: "midnight-script-ink-set",
    name: "Midnight Script Ink Set",
    tagline: "Dark phrase tattoos with a sharper edge",
    description: "A one-sheet waterproof tattoo set with statement script and graphic details designed for arms, collarbones, legs, and back placement.",
    price: 5,
    originalPrice: 8,
    image: "https://img.kwcdn.com/product/fmket/d2448c50109c200e3d858e4061b823a5.jpg",
    badge: "New",
    category: "tattoos",
    sizes: ["1 Sheet"],
    details: "The mix of compact phrase art and darker line work makes this a good fit for concerts, nightlife looks, and quick styled shoots.",
    howToUse: "Cut around each design, place on clean skin, and press with a damp cloth until the backing slides away. Remove with oil or balm cleanser.",
    ingredients: "Water-transfer pigment layer, safe cosmetic adhesive, and protective transfer sheet.",
    delivery: tattooDelivery,
  },
  {
    id: "rose-glow-mini-ink-pack",
    name: "Rose Glow Mini Ink Pack",
    tagline: "Small romantic tattoos for soft styling",
    description: "A five-piece mini tattoo pack with sweet phrase artwork designed for wrists, ankles, shoulders, and layered date-night looks.",
    price: 7,
    originalPrice: 11,
    image: "https://img.kwcdn.com/product/fancy/377e1a1d-63f0-4084-bb82-e979ec6d58b7.jpg",
    badge: "New",
    category: "tattoos",
    sizes: ["5 Pieces"],
    details: "Each mini design is sized for subtle placement so you can scatter several tattoos across one look without it feeling too heavy.",
    howToUse: "Press each piece onto clean dry skin with water and let it dry fully before adding lotion or clothing over the area.",
    ingredients: "Temporary transfer pigment, lightweight adhesive film, and paper backing sheets.",
    delivery: tattooDelivery,
  },
]

export const shopProducts = catalogProducts.map(({ id, name, description, price, originalPrice, image, badge, category }) => ({
  id,
  name,
  description,
  price,
  originalPrice,
  image,
  badge,
  category,
}))

export function getProductById(id: string) {
  return catalogProducts.find((product) => product.id === id)
}

export function getProductSeoImagePath(id: string) {
  return `/product/${id}/opengraph-image`
}
